name: Build and Release Binaries

on:
  # Trigger on pushing a tag that starts with 'v', e.g. 'v1.0.0'
  push:
    tags:
      - 'v*'

jobs:
  # ---------------------------
  # 1) Build for all targets
  # ---------------------------
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - x86_64-apple-darwin
    runs-on: ${{ matrix.target == 'x86_64-apple-darwin' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Add macOS target
        if: matrix.target == 'x86_64-apple-darwin'
        run: rustup target add x86_64-apple-darwin

      - name: Install cross
        if: matrix.target != 'x86_64-apple-darwin'
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: |
          if [ "${{ matrix.target }}" == "x86_64-apple-darwin" ]; then
            cargo build --release --target ${{ matrix.target }}
          else
            cross build --release --target ${{ matrix.target }}
          fi

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts/${{ matrix.target }}
          if [[ "${{ matrix.target }}" == *"windows-gnu" ]]; then
            cp target/${{ matrix.target }}/release/r2md.exe artifacts/${{ matrix.target }}/r2md.exe
          else
            cp target/${{ matrix.target }}/release/r2md artifacts/${{ matrix.target }}/r2md
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: artifacts/${{ matrix.target }}

  # ---------------------------
  # 2) Create GitHub Release
  #    and upload binaries
  # ---------------------------
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v3
        with:
          name: x86_64-unknown-linux-gnu
          path: artifacts/x86_64-unknown-linux-gnu

      - name: Download Windows artifact
        uses: actions/download-artifact@v3
        with:
          name: x86_64-pc-windows-gnu
          path: artifacts/x86_64-pc-windows-gnu

      - name: Download macOS artifact
        uses: actions/download-artifact@v3
        with:
          name: x86_64-apple-darwin
          path: artifacts/x86_64-apple-darwin

      - name: Create/Update Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          prerelease: false
  


      - name: Upload Linux Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/x86_64-unknown-linux-gnu/r2md
          asset_name: r2md-x86_64-unknown-linux-gnu

      - name: Upload Windows Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/x86_64-pc-windows-gnu/r2md.exe
          asset_name: r2md-x86_64-pc-windows-gnu.exe

      - name: Upload macOS Binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: artifacts/x86_64-apple-darwin/r2md
          asset_name: r2md-x86_64-apple-darwin
